xenditApiBasedUrl=https://api.xendit.co
xenditSandboxPathUrl=/fixed_payment_code/simulate_payment 
tokenXenditApi=Basic eG5kX2RldmVsb3BtZW50XzhtaHBBd25TZDduVXlpOXFyZlNzaXNFMmpjdzlibUczZDNCV0NLVlBib0dlcFd1bkdGSzFUQndGRWhCOg==