browserName=chrome
headless=false
devTools=false
slowMo=1000.00
defaultNavigationTimeout=3e4
defaultTimeout=15000
longWaitTime=12e4
setAcceptDownload=false
setVideoRecord=false
setTracing=true
ci/cd=false