#should be staging or prod
env=stag
mainUrl_stag=https://jambu.kerupux.com
mainUrl_prod=https://mamikos.com
ownerUrl_stag=https://owner-jambu.kerupux.com
ownerUrl_prod=
generalPassword=qwerty123
adminEmail=
adminmamipay1=automationpman03@mamikos.com
#Backoffice URL
backoffice_stag=https://pay-jambu.kerupux.com/pin2blkang/
backoffice_prod=https://bang-pay.kerupux.com/pin2blkang/
#direct navigate URL
kostSayaBilling=/user/kost-saya/billing
tenantEditProfile=/user/edit-profil
tenantRiwayatBooking=/user/booking/
ownerKelolaTagihan=/billing-management
favoritePage=/history/favourite
kostMurahDiJogja=/kost/kost-jogja-murah
kost=/kost
booking=/booking
promoKost=/promo-kost
history=/history
ugmKostList=/cari/ugm/all/bulanan/0-15000000