v3prefix=/web_api
xGitTime=1596244631

#Tenant Endpoint Block
tenantProfile=/garuda/user/profile
createBooking=/garuda/user/booking/39645784/6230
#/garuda/user/booking/{roomId}/{roomTypeId}
#Tenant Endpoint Block
