#should be staging or prod

#ENV
env=stag
#ENV

#Base URL
mainUrl_stag=https://jambu.kerupux.com
mainUrl_prod=https://mamikos.com
ownerUrl_stag=https://owner-jambu.kerupux.com
ownerUrl_prod=
#Base URL

#General Password
generalPassword=qwerty123

#Admin Block
adminEmail=
adminmamipay1=automationpman03@mamikos.com
#Backoffice URL
backoffice_stag=https://pay-jambu.kerupux.com
backoffice_prod=https://bang-pay.kerupux.com
bangkrupux_stag=https://jambu.kerupux.com/admin/
PMSUrl_stag=https://sini-jambu.kerupux.com/login
PMSUrl_prod=https://singgahsini.kerupux.com/login
loginMamipay =/pin2blkang
adminGoldplusPackage = /admin/gold-plus/package
#Admin Block

#direct navigate URL
#direct navigate URL Only please do not put any admin relate link to below lines.
kostSayaBilling=/user/kost-saya/billing
tenantEditProfile=/user/edit-profil
tenantRiwayatBooking=/user/booking/
ownerKelolaTagihan=/billing-management
favoritePage=/history/favourite
kostMurahDiJogja=/kost/kost-jogja-murah
kost=/kost
booking=/booking
promoKost=/promo-kost
history=/history
ugmKostList=/cari/ugm/all/bulanan/0-15000000
promoNgebut=/promo-ngebut
promoNgebutArea=/kost-promo-ngebut
promoNgebutAreaTop=/kost-promo-ngebut?from=top
promoNgebutAreaBottom=/kost-promo-ngebut?from=bottom
apartment=/apartemen
ownerKos=/ownerpage/kos
goldplusTestingTools = /backoffice/testing-tools/goldplus
voucherSaya=/user/voucherku
searchInvoice=/backoffice/invoice/search
tenantRiwayatKost=/user/riwayat-kos
pengajuanBooking=/booking/request
oldProPhoto = /prophoto
mamifoto =/mamifoto
kostSaya =/user/kost-saya
kontrakKostSaya =/user/kost-saya/contract
mamipoinGuideline =/user/mamipoin/guideline
helpPage = /user/kost-saya/help
penyewa  = /tenant-list?status=all
mamikosVoucher = /backoffice/voucher
mamipoinExpired =/user/mamipoin/expired
mamipoinHistory =/user/mamipoin/history
mamikosApartemen =/ownerpage/apartment
ownerSetting = /ownerpage/settings
broadcastChat = /broadcast-chat
propertyApartement = /ownerpage/apartment
mamiads = /mamiads
mamiadsFromOwnerDashboard = /mamiads?redirectionSource=Owner%20Dashboard
cekPropertySekitar = /cek-properti-sekitar
mamiadsBalance = /mamiads/balance
