v3prefix=/web_api
xGitTime=1596244631
v1prefix=/api/v1
bakpao=http://bakpao1.kerupux.com
garuda=/garuda

#Tenant Endpoint Block
createDeviceId=/auth/device/register?device_identifier=%s&device_uuid=%s&device_platform=%s
tenantLogin=/auth/tenant/login?password=%s
tenantProfile=/garuda/user/profile
tenantBookingList=/user/booking?page=%s&sort=%s&status=%s
tenantBatalkanBookingReason=/booking/get-reject-reason/cancel
tenantBatalkanBooking=/user/booking/cancel/MAMI0808074577
#Tenant Endpoint Block

#Owner Endpoint Block
ownerLogin=/auth/owner/login
#Owner Endpoint Block
