#should be staging or prod

#ENV
env=stag
#ENV

#Base URL
mainUrl_stag=https://jambu.kerupux.com
mainUrl_prod=https://mamikos.com
ownerUrl_stag=https://owner-jambu.kerupux.com
promoMamikosURL_prod = https://promo.mamikos.com/
ownerUrl_prod=https://owner.mamikos.com
ownersiniUrl_stag=https://ownersini-jambu.kerupux.com/
ownersiniUrl_prod=https://owner.singgahsini.id/
singgahsiniUrl_stag=https://singgahsini-landing.kerupux.com
singgahsiniUrl_prod=https://singgahsini.id
checkPropertyUrl_stag=https://jambu.kerupux.com/cek-properti
lctUrl_stag=https://jambu.kerupux.com/leads/agen/leads-management
lctUrl_prod=https://mamikos.com/leads/agen/leads-management

#Base URL

#General Password
generalPassword=qwerty123

#Admin Block
adminEmail=
adminmamipay1=automationpman03@mamikos.com
#Backoffice URL
backoffice_stag=https://pay-jambu.kerupux.com
backoffice_prod=https://bang-pay.kerupux.com
bangkrupux_stag=https://jambu.kerupux.com/admin
bangkrupux_prod=https://bang.kerupux.com/auth
PMSUrl_stag=https://sini-jambu.kerupux.com/login
PMSUrl_prod=https://singgahsini.kerupux.com/login
loginMamipay =/pin2blkang
adminGoldplusPackage = /admin/gold-plus/package
logiPemilikUrl_stag=https://jambu.kerupux.com/login-pemilik
logiPemilikUrl_prod=https://mamikos.com/login-pemilik
mamitourOrder = /admin/mamitour
loginUSer = https://jambu.kerupux.com/login
#Admin Block

#direct navigate URL
redirectOwner_stag=?redirect_url=https://jambu.kerupux.com
#direct navigate URL Only please do not put any admin relate link to below lines.
kostSayaBilling=/user/kost-saya/billing
tenantEditProfile=/user/edit-profil
tenantRiwayatBooking=/user/booking/
ownerKelolaTagihan=/billing-management
favoritePage=/history/favourite
kostMurahDiJogja=/kost/kost-jogja-murah
kost=/kost
booking=/booking
promoKost=/promo-kost
history=/history
nologin=/login-pencari
ugmKostList=/cari/ugm/all/bulanan/0-15000000
promoNgebut=/promo-ngebut
promoNgebutArea=/kost-promo-ngebut
promoNgebutAreaTop=/kost-promo-ngebut?from=top
promoNgebutAreaBottom=/kost-promo-ngebut?from=bottom
apartment=/apartemen
ownerKos=/ownerpage/kos
goldplusTestingTools = /backoffice/testing-tools/goldplus
voucherSaya=/user/voucherku
searchInvoice=/backoffice/invoice/search
tenantRiwayatKost=/user/riwayat-kos
pengajuanBooking=/booking/request
oldProPhoto = /prophoto
mamifoto =/mamifoto
kostSaya =/user/kost-saya
kontrakKostSaya =/user/kost-saya/contract
mamipoinGuideline =/user/mamipoin/guideline
helpPage = /user/kost-saya/help
penyewa  = /tenant-list?status=all
mamikosVoucher = /backoffice/voucher
mamipoinExpired =/user/mamipoin/expired
mamipoinHistory =/user/mamipoin/history
mamikosApartemen =/ownerpage/apartment
ownerSetting = /ownerpage/settings
broadcastChat = /broadcast-chat
propertyApartement = /ownerpage/apartment
mamiads = /mamiads
mamiadsFromOwnerDashboard = /mamiads/balance
cekPropertySekitar = /cek-properti-sekitar
mamiadsBalance = /mamiads/balance
mamiadsGuide = /goldplus/guides/advertisement_usage?redirect=mamikos
mamiadsGuideGP = /goldplus/guides
mamiadsHistory = /mamiads/history
goldplusContract = /backoffice/goldplus/contracts
kontrakKerjaSama = https://sini-jambu.kerupux.com/property-detail/3143/contract
mamipayOwnerList = /backoffice/owner
goldplusPackage = /goldplus/submission/packages
goldplusPackage2 = /goldplus/submission/periode/gp2
goldplusPackage1 = /goldplus/submission/periode/gp1
mamitour = /mamitour
helpMamitour = /category/pemilik/layanan-pendukung/mamitour
financialReport = /financial-report
goldplus2Package = /goldplus/submission/periode/gp2
formulirDataPenyewa = /ob/dbet-4L8PYJ96/onboarding
statisticPPRS = /statistic
addContractTenant = /add-tenant/select-method
rulesEnterKos = /booking-setting
mamiprimePendaftaran = /prime/package/
mamiprime = /prime
historyMamiprime = /prime/history?type=on-progress
mamiprimeTestingTools = /backoffice/testing-tools/mamiprime
mamiprimeSuggestion = /admin/prime-suggestion
ownerEditKos= /kos/edit?kosId=
ownerKosRoomsPrice = /kos/rooms-price
kosPrice= /kos/price/
ownerPageKos= /ownerpage/kos
partnerPortalUrl=/partner