v3prefix=web_api/
v1prefix=api/v1/
bakpao=http://bakpao1.kerupux.com/
jambu=https://jambu.kerupux.com/
garuda=garuda/
xGitTime=1663812252
develAccessToken=858927937bd4a94bd06f5a2bb87f95f62241390ec4158b9b01becbee3d1d31d6
secretKey=596870d89f4daf33406f69fd1aa200030d7d859341b0c32b2977e0333d0200ec

#Tenant Endpoint Block
createDeviceId=auth/device/register
tenantLogin=auth/tenant/login
tenantProfile=user/profile
createBooking=user/booking/{songId}/{roomTypeId}
tenantBookingList=user/booking
tenantBatalkanBookingReason=booking/get-reject-reason/cancel
tenantBatalkanBooking=user/booking/cancel/{bookingId}
kosDetail=user/booking/detail-room
#Tenant Endpoint Block

#Owner Endpoint Block
ownerLogin=auth/owner/login
ownerProfile=owner/data/profile
roomAllotment=https://jambu.kerupux.com/user/mamipay/request/owner/booking/room-allotment/58650684?start_date=2023-09-15&end_date=2023-10-15
ownerAcceptBooking=https://jambu.kerupux.com/ownerpage/mamipay/request/owner/booking/accept/76483
ownerBookingList=user/booking/detail/20363
#/oauth/mamipay/request/owner/booking?offset=0&group[]=0&order=desc&limit=5
#Owner Endpoint Block
